apiVersion: apps/v1
kind: Deployment
metadata:
  name: raghu-app
  labels:
    app: raghu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raghu-app
  template:
    metadata:
      labels:
        app: raghu-app
    spec:
      imagePullSecrets:
        - name: gar-secret
      containers:
        - name: raghu-container
          # Harness will replace this with the artifact image from CI.
          # deployment.yaml
          image: nagasaivardhan/app:blue
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-blue
spec:
  selector:
    app: raghu-app
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      protocol: "TCP"
       
