apiVersion: apps/v1
kind: Deployment
metadata:
  name: raghu-app
  labels:
    app: raghu-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raghu-app
  template:
    metadata:
      labels:
        app: raghu-app
    spec:
      containers:
        - name: raghu-container
          # Harness will replace this with the artifact image from CI.
          # deployment.yaml
          image: {{.Values.image}}
          ports:
            - containerPort: 80
       
